# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release

pool:
  vmImage: ubuntu-latest
jobs:
- job: Zip
  displayName: 'Zip and Publish'
  workspace:
    clean: all
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: Compress-Archive -Path $(Agent.BuildDirectory) -DestinationPath $(Build.ArtifactStagingDirectory)\PerformanceMixerBeta-$(Build.BuildNumber).zip -Force